---
title: "Henry_testing"
format: html
---

```{r}
library(tidyverse)
library(rvest)
library(polite)
library(httr)
```


Here is a script to get the gamne IDs of the top 100 games on steam.


```{r}

usethis::edit_r_environ("project")

parse_genres <- function(genres_list) {
  genres = character()
  for (genre in genres_list) {
    genres <- c(genres, genre$description)
  }
  return(paste(genres, collapse = ", "))
}

```


```{r}
get_steam_game <- function(appid) {

response <- GET(str_c("https://store.steampowered.com/api/appdetails?appids=", appid, "&cc=us"))
data <- content(response, "parsed")
game <- data[[as.character(appid)]]$data

str(game)


  list(
    name       = game$name,
    price      = game$price_overview$final_formatted,
    genres     = parse_genres(game$genres),
    reviews    = game$recommendations$total,
    release    = game$release_date$date,
    developer  = paste(game$developers, collapse = ", ")
  )

}





#get_steam_game(413150)

#get_steam_game(105600)

get_steam_game()
```

```{r}

  
response <- GET(str_c("https://api.steampowered.com/ISteamApps/GetAppList/v2/"))
data <- content(response, "parsed")

data
```


