---
title: 'scraping_code'
format:
  pdf: default
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: FALSE

library(tidyverse)
library(purrr)
library(rvest)
library(polite)
library(httr)
library(readr)
library(tidytext)
```


```{r}

#' Scrape a games Steam reviews.
#'
#' This function takes in a 
#' Steam appid and returns 100 random reviews.
#'
#' @param appid A Steam appid
#' @return A tibble with game data 

scrape_reviews <- function(appid, num_reviews = 500) {
  all_reviews <- list()
  cursor <- "*"
  
  repeat {
      game_response <- GET(
        str_c("https://store.steampowered.com/appreviews/", appid, "?json=1"),
        query = list(
          filter        = "all",
          language      = "english",
          review_type   = "all",
          purchase_type = "all",
          num_per_page  = 100,
          cursor        = cursor
        )
      )
      
    if (status_code(game_response) == 429) {
      message("Rate limited, taking a 30s break")
      Sys.sleep(30)
      next  # retry same cursor(page)
    }
      
    if (status_code(game_response) != 200) {
      message(str_c("Bad status", status_code(game_response), "for appid", appid))
      break
    }
      
    raw_data <- content(game_response, "parsed")
    
    if (length(raw_data$reviews) == 0) break
    
    for (i in seq_along(raw_data$reviews)) {
      r <- raw_data$reviews[[i]]
      all_reviews[[length(all_reviews) + 1]] <- tibble(
        appid         = appid,
        text          = r$review,
        positive      = r$voted_up,
        playtime_hrs  = r$author$playtime_forever / 60,
        helpful_votes = r$votes_up,
      )
    }
    
    # Stop if we have enough or no more pages
    if (length(all_reviews) >= num_reviews || is.null(raw_data$cursor)) {
      break
    }
    
    cursor <- raw_data$cursor
    Sys.sleep(0.5)
  }
  
  if (length(all_reviews) == 0) {
    return(NULL)
  }
  
  reviews <- bind_rows(all_reviews) |>
    mutate(text_clean = str_remove_all(text, "♥+")) |>
    filter(str_detect(text_clean, "^[[:ascii:]]+$")) |>
    distinct(text_clean, .keep_all = TRUE)
  
  return(reviews)
}
```



```{r}
#| warning: false
#| message: false


# Manual scrape of top 400 peak games app_ids
games_df <- read.csv("data/app_ids.csv", header = FALSE)
games <- as.vector(unlist(games_df[1, ]))

# Scrape review data
review_tibbles <- map(games, scrape_reviews)
review_data <- bind_rows(review_tibbles)

write_csv(review_data, "data/video_games_review.csv")

```


```{r}
games_df <- read.csv("data/video_games_updated.csv")
review_data <- read.csv("data/video_games_review.csv")
```

```{r}
review_data <- review_data |>
  left_join(games_df |> select(appid, name, genres), by = "appid")
```

```{r}
review_data <- review_data |>
  filter(
    str_length(text_clean) > 20,                     
    !str_detect(text, "(.)\\1{4,}"),                  
    str_count(text_clean, "\\w+") > 5,
    !genres == "" & !is.na(genres)) |>
  mutate(text_clean = 
    str_remove_all(text_clean, "[^a-zA-Z\\s]")) |>
  distinct()
```




```{r}
review_data |>
  separate_rows(genres, sep = ", ") |>
  unnest_tokens(word, text_clean) |>
  anti_join(stop_words) |> 
  inner_join(get_sentiments("bing"), relationship = "many-to-many") |>
  group_by(genres) |>
  summarise(sentiment_score = mean(sentiment == "positive") - mean(sentiment == "negative")) |>
  arrange(desc(sentiment_score))
```



```{r}
review_data |>
  unnest_tokens(word, text_clean) |>
  anti_join(stop_words) |>  
  separate_rows(genres, sep = ", ") |>
  count(genres, word) |>
  bind_tf_idf(word, genres, n) |>
  arrange(desc(tf_idf)) |>
  filter(genres == "Indie")
```


```{r}
review_data |>
  unnest_tokens(bigram, text, token = "ngrams", n = 2) |>
  separate_rows(genres, sep = ", ") |>
  filter(bigram != "NA")  |>
  separate(bigram, c("word1", "word2"), sep = " ") |>
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word) |>
  count(word1, word2, sort = TRUE)
```

